[window]
opacity = 1.0

padding = { x = 4, y = 4 }

[scrolling]
history = 2000

[font]
size = 10.0

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.italic]
family = "JetBrainsMono NF"
style = "Italic" 

[bell]
duration = 0 

[cursor]
style = { shape = "Block", blinking = "Off" }

[colors]

[colors.primary]
background = "#12140d"
foreground = "#e3e3d7"

[colors.cursor]
text   = "#12140d"
cursor = "#b9cf83"

[colors.selection]
text       = "#12140d"
background = "#b9cf83"

[colors.normal]
black   = "#c6c8b8"
red     = "#ffb4ab"
green   = "#b9cf83"
yellow  = "#a1d0c7"
blue    = "#d4ec9d"
magenta = "#dee6c5"
cyan    = "#c2caaa"
white   = "#e3e3d7"

[colors.bright]
black   = "#c6c8b8"
red     = "#ffb4ab"
green   = "#b9cf83"
yellow  = "#a1d0c7"
blue    = "#d4ec9d"
magenta = "#dee6c5"
cyan    = "#c2caaa"
white   = "#e3e3d7"