[window]
opacity = 1.0

padding = { x = 4, y = 4 }

[scrolling]
history = 2000

[font]
size = 10.0

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.italic]
family = "JetBrainsMono NF"
style = "Italic" 

[bell]
duration = 0 

[cursor]
style = { shape = "Block", blinking = "Off" }

[colors]

[colors.primary]
background = "#16130b"
foreground = "#e9e2d4"

[colors.cursor]
text   = "#16130b"
cursor = "#dfc56d"

[colors.selection]
text       = "#16130b"
background = "#dfc56d"

[colors.normal]
black   = "#cec6b4"
red     = "#ffb4ab"
green   = "#dfc56d"
yellow  = "#abd0b1"
blue    = "#fce186"
magenta = "#f0e2bb"
cyan    = "#d3c6a1"
white   = "#e9e2d4"

[colors.bright]
black   = "#cec6b4"
red     = "#ffb4ab"
green   = "#dfc56d"
yellow  = "#abd0b1"
blue    = "#fce186"
magenta = "#f0e2bb"
cyan    = "#d3c6a1"
white   = "#e9e2d4"